### ISSUE TITLE
I followed the installation instructions but it doesn't work

### ISSUE THREAD

**Issue by davelab6** [Homebrew/homebrew-command-not-found#29]
I followed the installation instructions but it doesn't work

```bash
$ brew install bash;
$ brew tap homebrew/command-not-found;
$ # edit .bash_profile
$ tail -n3 .bash_profile;
if brew command command-not-found-init > /dev/null; then
  eval "$(brew command-not-found-init)";
fi
$ source .bash_profile;
$ when
-bash: when: command not found
$
```

**Comment by bfontaine** [comment]
Does `$(brew --prefix)/bin/bash -ic when` work? If so it’s because you ran this with the default Bash; installing Bash 4.x doesn’t replace the currently running session. `brew install bash` should have printed the following:
```
==> Caveats
In order to use this build of bash as your login shell,
it must be added to /etc/shells.
```

Let me know if that fixes the issue; we might need to update the README to clarify this.

**Comment by davelab6** [comment]
Aha! I'll make a PR, but I now have:

```
$ when
The program 'when' is currently not installed. You can install it by typing:
  brew install when
```
