### ISSUE TITLE
command-not-found causes VERY long zsh startup times

### ISSUE THREAD

**Issue by vegerot** [Homebrew/homebrew-command-not-found#56]
This is my `zshrc`
```
start=`gdate +%s.%N`
export ZSH="$HOME/.oh-my-zsh"
fpath=(/usr/local/share/zsh-completions /usr/local/share/zsh-completions/conda-zsh-completion $fpath)
source $ZSH/oh-my-zsh.sh

end=`gdate +%s.%N`
runtime=$( echo "$end - $start"|bc -l )
echo "$runtime seconds"
```

when I open `zsh` the output is always around `.118130000 seconds`

Now when I try adding `command-not found`:

```
start=`gdate +%s.%N`
export ZSH="$HOME/.oh-my-zsh"
fpath=(/usr/local/share/zsh-completions /usr/local/share/zsh-completions/conda-zsh-completion $fpath)
if brew command command-not-found-init > /dev/null; then
  eval "$(brew command-not-found-init)";
fi
source $ZSH/oh-my-zsh.sh

end=`gdate +%s.%N`
runtime=$( echo "$end - $start"|bc -l )
echo "$runtime seconds"
```

Now when I open `zsh`, the output is around `2.358168000 seconds`!

Clearly, this is unacceptable.  What can be done to speed this up?

**Comment by bfontaine** [comment]
Can you confirm `time brew command ls` or `time brew help` give normal run times?

It’s also very slow on my machine but it’s due to Homebrew itself, as every `brew` invocation appears to have a ~1.8s overhead.

**Comment by vegerot** [comment]
@bfontaine as you said, there is an overhead from `brew`.
```
/usr/local/Homebrew/Library/Homebrew/cmd/list.rb
brew command ls  0.64s user 0.62s system 94% cpu 1.340 total
```

**Comment by bfontaine** [comment]
Yep, I agree on the overhead. I _feel_ like it’s recent as I don’t remember having any slowness issue when I originally created the command.

In the end, all the Ruby command does is check your shell and dump the appropriate handler -- [`handler.sh`](https://github.com/Homebrew/homebrew-command-not-found/blob/master/handler.sh) for Bash/Zsh or [`handler.fish`](https://github.com/Homebrew/homebrew-command-not-found/blob/master/handler.fish) for Fish.

That shell part defines the `command-not-found` hook and registers it for the current session. It can’t be asynchronous because it must run in the current shell.

I’m not on a Mac right now but something like this should feel instantaneous:

```shell
HB_CNF_HANDER="$(brew --prefix)/Homebrew/Library/Taps/homebrew/homebrew-command-not-found/handler.sh"
if [ -f "$HB_CNF_HANDER" ]; then
  source "$HB_CNF_HANDER";
fi
```

`brew --prefix` returns before Homebrew starts loading Ruby, so it doesn’t suffer from its performance issues.

**Comment by vegerot** [comment]
So should I/someone make a PR fixing this?

**Comment by bfontaine** [comment]
Yes, that would be great!

**Comment by andrewarchi** [comment]
I've been seeing slow startup times myself as well, in my case with Bash's .bash_profile. Is there a planned PR for this?

**Comment by vegerot** [comment]
@andrewarchi I might work on a PR if I have some free time
