### ISSUE TITLE
homebrew-command-not-found started displaying error on loading on macOS

### ISSUE THREAD

**Issue by andrewcrook** [Homebrew/homebrew-command-not-found#64]
# Issue
Started up a terminal on macOS this morning and got the following error.

# Error
```sh 
Error:' uninitialized constant Utils::Shell
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-command-not-found/cmd/brew-command-not-found-init.rb:4:in 'shell'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-command-not-found/cmd/brew-command-not-found-init.rb:45:in 'init'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-command-not-found/cmd/brew-command-not-found-init.rb:58:in '<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in 'require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in 'require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:85:in 'require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:121:in '<main>'
```

# Temp Fix
removing the homebrew-command-not-found tap resolves it 
```
> brew untap homebrew/command-not-found
```

# System Details 

* MacOS: 10.15.6 (19G2021)
* Xcode : Version 11.6 (11E708)

* Homebrew
```
> brew --version
Homebrew 2.4.13-41-g236cbbc
Homebrew/homebrew-core (git revision 90eb3; last commit 2020-08-22)
Homebrew/homebrew-cask (git revision 4602d; last commit 2020-08-22)
```

* Defualt System Ruby (with macOS Catalina)
```
>  ruby -v
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
```

* Brew Ruby
```
> pwd
/usr/local/Cellar/ruby/2.7.1_2/bin
> ./ruby -v
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]
```

* Other

Possibly caused by Brew update on the 22/08/2020 ?
```
Homebrew/homebrew-core (git revision 90eb3; last commit 2020-08-22)
Homebrew/homebrew-cask (git revision 4602d; last commit 2020-08-22)
```

**Comment by bfontaine** [comment]
Thanks for the report! Sorry, I was away for the weekend. I just fixed the first issue (error message; https://github.com/Homebrew/homebrew-command-not-found/commit/0a6cff153fe2819a26fa118dac41e52aa1ababec) as well as the second (doesn’t work; https://github.com/Homebrew/homebrew-command-not-found/commit/5d0556b1acbff096aeb796139a3056e3319fc63f).

As far as I understand, Homebrew is increasingly moving from code where constants and classes are explicitely required rather than being globally available. This is a good thing, but it breaks code that rely on that global availability, like here.
